
 const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_CART_FROM_CHECK_OUT: 'CLEAR_ITEM_CART_FROM_CHECK_OUT',
    REMOVE_QUANTITY: 'REMOVE_QUANTITY'
}

export default CartActionTypes;